# Generated by Django 5.1.2 on 2024-11-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='encrypted_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='iv',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='tag',
            field=models.CharField(default='', max_length=24),
        ),
    ]
