# Generated by Django 5.1.2 on 2024-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_vault', '0002_passwordentry_encrypted_password_passwordentry_iv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordentry',
            name='password_entry',
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='encrypted_password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='iv',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='tag',
            field=models.CharField(max_length=24),
        ),
    ]
