# Generated by Django 5.1.2 on 2024-11-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_vault', '0003_remove_passwordentry_password_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='password_entry',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
