# Generated by Django 5.1.2 on 2024-11-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_vault', '0004_passwordentry_password_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordentry',
            name='password_entry',
        ),
    ]
