# Generated by Django 5.1.2 on 2024-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_vault', '0005_remove_passwordentry_password_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
